

VERILOG_SOURCES = $(shell pwd)/../reg_file.v
VERILOG_SOURCES += $(shell pwd)/reg_file_wrapper.v

TOPLEVEL := reg_file_wrapper
MODULE   := test

include $(shell cocotb-config --makefiles)/Makefile.sim